#pos(sampled61s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,5). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled61s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s8, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,5). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s23, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled61s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled61s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s38, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled61s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled61s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled41s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s5, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,7). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled41s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s24, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,2). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled41s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,6). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@5, sampled61s0, sampled41s0, >).
#brave_ordering(o2@5, sampled61s1, sampled41s1, >).
#brave_ordering(o3@5, sampled61s2, sampled41s2, >).
#brave_ordering(o4@5, sampled61s3, sampled41s3, >).
#brave_ordering(o5@5, sampled61s4, sampled41s4, >).
#brave_ordering(o6@3, sampled61s5, sampled41s5, <).
#brave_ordering(o7@5, sampled61s6, sampled41s6, >).
#brave_ordering(o8@5, sampled61s7, sampled41s7, >).
#brave_ordering(o9@3, sampled61s8, sampled41s8, >).
#brave_ordering(o10@5, sampled61s9, sampled41s9, >).
#brave_ordering(o11@5, sampled61s10, sampled41s10, >).
#brave_ordering(o12@3, sampled61s11, sampled41s11, <).
#brave_ordering(o13@5, sampled61s12, sampled41s12, >).
#brave_ordering(o14@5, sampled61s13, sampled41s13, >).
#brave_ordering(o15@5, sampled61s14, sampled41s14, >).
#brave_ordering(o16@3, sampled61s15, sampled41s15, >).
#brave_ordering(o17@5, sampled61s16, sampled41s16, >).
#brave_ordering(o18@4, sampled61s17, sampled41s17, >).
#brave_ordering(o19@4, sampled61s18, sampled41s18, >).
#brave_ordering(o20@4, sampled61s19, sampled41s19, >).
#brave_ordering(o21@6, sampled61s20, sampled41s20, >).
#brave_ordering(o22@4, sampled61s21, sampled41s21, >).
#brave_ordering(o23@4, sampled61s22, sampled41s22, >).
#brave_ordering(o24@3, sampled61s23, sampled41s23, >).
#brave_ordering(o25@3, sampled61s24, sampled41s24, <).
#brave_ordering(o26@5, sampled61s25, sampled41s25, >).
#brave_ordering(o27@4, sampled61s26, sampled41s26, >).
#brave_ordering(o28@4, sampled61s27, sampled41s27, >).
#brave_ordering(o29@4, sampled61s28, sampled41s28, >).
#brave_ordering(o30@4, sampled61s29, sampled41s29, >).
#brave_ordering(o31@4, sampled61s30, sampled41s30, >).
#brave_ordering(o32@4, sampled61s31, sampled41s31, >).
#brave_ordering(o33@4, sampled61s32, sampled41s32, >).
#brave_ordering(o34@4, sampled61s33, sampled41s33, >).
#brave_ordering(o35@5, sampled61s34, sampled41s34, >).
#brave_ordering(o36@4, sampled61s35, sampled41s35, >).
#brave_ordering(o37@4, sampled61s36, sampled41s36, >).
#brave_ordering(o38@4, sampled61s37, sampled41s37, >).
#brave_ordering(o39@2, sampled61s38, sampled41s38, >).
#brave_ordering(o40@2, sampled61s39, sampled41s39, >).
#brave_ordering(o41@1, sampled61s40, sampled41s40, >).
#brave_ordering(o42@4, sampled61s41, sampled41s41, >).
#brave_ordering(o43@4, sampled61s42, sampled41s42, >).
#brave_ordering(o44@4, sampled61s43, sampled41s43, >).
#brave_ordering(o45@4, sampled61s44, sampled41s44, >).
