#pos(sampled9s0, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,104). value(uova,0). value(farinacei,5). value(frutta,2). value(erbe_spezie_e_condimenti,305). value(carne,303). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s1, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,304). value(carne,303). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s2, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,305). value(carne,304). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,400). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s3, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,100). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,305). value(carne,304). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,507). value(bollitura,0). value(rosolatura,0). value(frittura,404). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s4, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,3). value(frutta,5). value(erbe_spezie_e_condimenti,306). value(carne,302). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,508). value(bollitura,0). value(rosolatura,0). value(frittura,404). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s5, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,302). value(carne,301). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,502). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s6, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,5). value(frutta,2). value(erbe_spezie_e_condimenti,307). value(carne,303). value(funghi_e_tartufi,0). value(pasta,9). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,400). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s7, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,104). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,307). value(carne,302). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s8, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,305). value(carne,302). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled9s9, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,104). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,304). value(carne,301). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled9s10, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,305). value(carne,302). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,502). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s11, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,303). value(carne,302). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s12, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,303). value(carne,301). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s13, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,303). value(carne,303). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s14, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,304). value(carne,302). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,502). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled9s15, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,302). value(carne,302). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,502). value(bollitura,0). value(rosolatura,0). value(frittura,400). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled9s16, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,304). value(carne,301). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s17, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,303). value(carne,300). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled9s18, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,305). value(carne,303). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s19, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,305). value(carne,303). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s20, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,309). value(carne,304). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s21, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,105). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,303). value(carne,304). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,404). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s22, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,303). value(carne,304). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled9s23, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,305). value(carne,304). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled9s24, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,100). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,304). value(carne,300). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s25, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,302). value(carne,302). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s26, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,100). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,304). value(carne,301). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,400). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s27, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,100). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,305). value(carne,302). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,502). value(bollitura,0). value(rosolatura,0). value(frittura,400). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s28, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,305). value(carne,302). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s29, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,305). value(carne,303). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s30, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,104). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,302). value(carne,301). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s31, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,301). value(carne,302). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s32, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,304). value(carne,302). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,400). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s33, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,304). value(carne,302). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled9s34, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,303). value(carne,302). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,505). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s35, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,303). value(carne,301). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s36, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,5). value(frutta,1). value(erbe_spezie_e_condimenti,306). value(carne,303). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,507). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s37, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,309). value(carne,302). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s38, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,102). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,303). value(carne,302). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled9s39, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,303). value(carne,301). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,503). value(bollitura,0). value(rosolatura,0). value(frittura,402). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s40, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,104). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,308). value(carne,305). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled9s41, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,304). value(carne,302). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,403). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s42, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,304). value(carne,304). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,404). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled9s43, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,103). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,302). value(carne,300). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,506). value(bollitura,0). value(rosolatura,0). value(frittura,401). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled9s44, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,101). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,304). value(carne,304). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,504). value(bollitura,0). value(rosolatura,0). value(frittura,404). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,107). value(carne,3). value(funghi_e_tartufi,0). value(pasta,509). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled8s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,1). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,101). value(carne,0). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled8s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,104). value(carne,4). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled8s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,0). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,102). value(carne,4). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,107). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled8s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled8s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,509). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,309). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled8s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,102). value(carne,5). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,301). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,101). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,100). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled8s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,308). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled8s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,103). value(carne,1). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,101). value(carne,1). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled8s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled8s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,108). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@1, sampled9s0, sampled8s0, <).
#brave_ordering(o2@1, sampled9s1, sampled8s1, <).
#brave_ordering(o3@2, sampled9s2, sampled8s2, <).
#brave_ordering(o4@1, sampled9s3, sampled8s3, <).
#brave_ordering(o5@2, sampled9s4, sampled8s4, <).
#brave_ordering(o6@2, sampled9s5, sampled8s5, <).
#brave_ordering(o7@1, sampled9s6, sampled8s6, <).
#brave_ordering(o8@1, sampled9s7, sampled8s7, <).
#brave_ordering(o9@2, sampled9s8, sampled8s8, <).
#brave_ordering(o10@2, sampled9s9, sampled8s9, <).
#brave_ordering(o11@2, sampled9s10, sampled8s10, <).
#brave_ordering(o12@2, sampled9s11, sampled8s11, <).
#brave_ordering(o13@2, sampled9s12, sampled8s12, <).
#brave_ordering(o14@2, sampled9s13, sampled8s13, <).
#brave_ordering(o15@2, sampled9s14, sampled8s14, <).
#brave_ordering(o16@2, sampled9s15, sampled8s15, <).
#brave_ordering(o17@2, sampled9s16, sampled8s16, <).
#brave_ordering(o18@2, sampled9s17, sampled8s17, <).
#brave_ordering(o19@2, sampled9s18, sampled8s18, <).
#brave_ordering(o20@1, sampled9s19, sampled8s19, <).
#brave_ordering(o21@1, sampled9s20, sampled8s20, <).
#brave_ordering(o22@1, sampled9s21, sampled8s21, <).
#brave_ordering(o23@2, sampled9s22, sampled8s22, <).
#brave_ordering(o24@2, sampled9s23, sampled8s23, <).
#brave_ordering(o25@1, sampled9s24, sampled8s24, <).
#brave_ordering(o26@2, sampled9s25, sampled8s25, <).
#brave_ordering(o27@2, sampled9s26, sampled8s26, <).
#brave_ordering(o28@2, sampled9s27, sampled8s27, <).
#brave_ordering(o29@2, sampled9s28, sampled8s28, <).
#brave_ordering(o30@2, sampled9s29, sampled8s29, <).
#brave_ordering(o31@2, sampled9s30, sampled8s30, <).
#brave_ordering(o32@2, sampled9s31, sampled8s31, <).
#brave_ordering(o33@2, sampled9s32, sampled8s32, <).
#brave_ordering(o34@2, sampled9s33, sampled8s33, <).
#brave_ordering(o35@2, sampled9s34, sampled8s34, <).
#brave_ordering(o36@2, sampled9s35, sampled8s35, <).
#brave_ordering(o37@2, sampled9s36, sampled8s36, <).
#brave_ordering(o38@2, sampled9s37, sampled8s37, <).
#brave_ordering(o39@2, sampled9s38, sampled8s38, <).
#brave_ordering(o40@2, sampled9s39, sampled8s39, <).
#brave_ordering(o41@1, sampled9s40, sampled8s40, <).
#brave_ordering(o42@2, sampled9s41, sampled8s41, <).
#brave_ordering(o43@2, sampled9s42, sampled8s42, <).
#brave_ordering(o44@2, sampled9s43, sampled8s43, <).
#brave_ordering(o45@1, sampled9s44, sampled8s44, <).
