#pos(sampled16s0, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s1, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s2, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s3, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s4, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled16s5, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s6, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled16s7, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s8, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s9, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1008). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled16s10, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1001). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1009). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s11, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s12, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled16s13, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s14, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s15, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s16, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5005). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s17, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s18, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s19, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled16s20, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s21, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s22, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5001). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s23, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s24, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s25, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,5). value(frutta,5). value(erbe_spezie_e_condimenti,1008). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1008). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled16s26, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1007). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s27, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s28, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5005). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s29, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s30, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s31, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1009). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s32, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s33, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1002). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled16s34, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5009). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s35, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s36, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s37, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s38, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5000). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled16s39, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled16s40, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5009). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5005). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled16s41, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1002). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled16s42, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,0). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1001). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s43, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1008). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled16s44, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5005). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled4s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,3001). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,5). value(erbe_spezie_e_condimenti,1007). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1004). value(carne,3000). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled4s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled4s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,3000). value(funghi_e_tartufi,0). value(pasta,5008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3001). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1007). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,5). value(erbe_spezie_e_condimenti,1007). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled4s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3001). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled4s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1001). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1008). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled4s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,5). value(erbe_spezie_e_condimenti,1007). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5010). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,3000). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled4s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,3001). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,3003). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3004). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled4s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1001). value(carne,3001). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled4s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,3006). value(funghi_e_tartufi,0). value(pasta,5008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled4s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,3000). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled4s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled4s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,3002). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@2, sampled16s0, sampled4s0, <).
#brave_ordering(o2@2, sampled16s1, sampled4s1, <).
#brave_ordering(o3@3, sampled16s2, sampled4s2, <).
#brave_ordering(o4@3, sampled16s3, sampled4s3, <).
#brave_ordering(o5@3, sampled16s4, sampled4s4, <).
#brave_ordering(o6@4, sampled16s5, sampled4s5, <).
#brave_ordering(o7@2, sampled16s6, sampled4s6, <).
#brave_ordering(o8@2, sampled16s7, sampled4s7, <).
#brave_ordering(o9@4, sampled16s8, sampled4s8, <).
#brave_ordering(o10@3, sampled16s9, sampled4s9, <).
#brave_ordering(o11@3, sampled16s10, sampled4s10, <).
#brave_ordering(o12@4, sampled16s11, sampled4s11, <).
#brave_ordering(o13@4, sampled16s12, sampled4s12, <).
#brave_ordering(o14@3, sampled16s13, sampled4s13, <).
#brave_ordering(o15@3, sampled16s14, sampled4s14, <).
#brave_ordering(o16@2, sampled16s15, sampled4s15, <).
#brave_ordering(o17@2, sampled16s16, sampled4s16, <).
#brave_ordering(o18@2, sampled16s17, sampled4s17, <).
#brave_ordering(o19@4, sampled16s18, sampled4s18, <).
#brave_ordering(o20@2, sampled16s19, sampled4s19, <).
#brave_ordering(o21@3, sampled16s20, sampled4s20, <).
#brave_ordering(o22@2, sampled16s21, sampled4s21, <).
#brave_ordering(o23@3, sampled16s22, sampled4s22, <).
#brave_ordering(o24@2, sampled16s23, sampled4s23, <).
#brave_ordering(o25@3, sampled16s24, sampled4s24, <).
#brave_ordering(o26@2, sampled16s25, sampled4s25, <).
#brave_ordering(o27@2, sampled16s26, sampled4s26, <).
#brave_ordering(o28@3, sampled16s27, sampled4s27, <).
#brave_ordering(o29@1, sampled16s28, sampled4s28, <).
#brave_ordering(o30@3, sampled16s29, sampled4s29, <).
#brave_ordering(o31@3, sampled16s30, sampled4s30, <).
#brave_ordering(o32@2, sampled16s31, sampled4s31, <).
#brave_ordering(o33@3, sampled16s32, sampled4s32, <).
#brave_ordering(o34@2, sampled16s33, sampled4s33, <).
#brave_ordering(o35@3, sampled16s34, sampled4s34, <).
#brave_ordering(o36@2, sampled16s35, sampled4s35, <).
#brave_ordering(o37@3, sampled16s36, sampled4s36, <).
#brave_ordering(o38@4, sampled16s37, sampled4s37, <).
#brave_ordering(o39@3, sampled16s38, sampled4s38, <).
#brave_ordering(o40@3, sampled16s39, sampled4s39, <).
#brave_ordering(o41@3, sampled16s40, sampled4s40, <).
#brave_ordering(o42@2, sampled16s41, sampled4s41, <).
#brave_ordering(o43@4, sampled16s42, sampled4s42, <).
#brave_ordering(o44@3, sampled16s43, sampled4s43, <).
#brave_ordering(o45@2, sampled16s44, sampled4s44, <).
