#pos(sampled87s0, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s1, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled87s2, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled87s3, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s4, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4005). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s5, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s6, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,0). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4000). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled87s7, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled87s8, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s9, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s10, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1001). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled87s11, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s12, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s13, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s14, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s15, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1002). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4000). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled87s16, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,1007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s17, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s18, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s19, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s20, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s21, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s22, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s23, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4004). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s24, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s25, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s26, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s27, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s28, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s29, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s30, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s31, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s32, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled87s33, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1003). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s34, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s35, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s36, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s37, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,1). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s38, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s39, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s40, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled87s41, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled87s42, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4000). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled87s43, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled87s44, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,0). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s0, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s1, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s2, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s3, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,1003). value(carne,2004). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s4, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s5, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s6, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,1008). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s7, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s8, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s9, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s10, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s11, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s12, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s13, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s14, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s15, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s16, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s17, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,2004). value(funghi_e_tartufi,0). value(pasta,3006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s18, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3001). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s19, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s20, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1006). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s21, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s22, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,0). value(erbe_spezie_e_condimenti,1006). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s23, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2004). value(funghi_e_tartufi,0). value(pasta,3007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s24, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,2004). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s25, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s26, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,2000). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s27, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s28, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s29, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3001). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s30, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,2004). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s31, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1002). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s32, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1008). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,6). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s33, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,2004). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s34, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s35, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s36, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2001). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s37, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s38, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s39, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2000). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled79s40, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled79s41, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled79s42, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1004). value(carne,2002). value(funghi_e_tartufi,0). value(pasta,3004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled79s43, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled79s44, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,2003). value(funghi_e_tartufi,0). value(pasta,3009). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@3, sampled87s0, sampled79s0, <).
#brave_ordering(o2@2, sampled87s1, sampled79s1, <).
#brave_ordering(o3@2, sampled87s2, sampled79s2, <).
#brave_ordering(o4@3, sampled87s3, sampled79s3, <).
#brave_ordering(o5@1, sampled87s4, sampled79s4, <).
#brave_ordering(o6@3, sampled87s5, sampled79s5, <).
#brave_ordering(o7@2, sampled87s6, sampled79s6, <).
#brave_ordering(o8@3, sampled87s7, sampled79s7, <).
#brave_ordering(o9@2, sampled87s8, sampled79s8, <).
#brave_ordering(o10@2, sampled87s9, sampled79s9, <).
#brave_ordering(o11@3, sampled87s10, sampled79s10, <).
#brave_ordering(o12@3, sampled87s11, sampled79s11, <).
#brave_ordering(o13@2, sampled87s12, sampled79s12, <).
#brave_ordering(o14@3, sampled87s13, sampled79s13, <).
#brave_ordering(o15@3, sampled87s14, sampled79s14, <).
#brave_ordering(o16@3, sampled87s15, sampled79s15, <).
#brave_ordering(o17@2, sampled87s16, sampled79s16, <).
#brave_ordering(o18@2, sampled87s17, sampled79s17, <).
#brave_ordering(o19@3, sampled87s18, sampled79s18, <).
#brave_ordering(o20@3, sampled87s19, sampled79s19, <).
#brave_ordering(o21@2, sampled87s20, sampled79s20, <).
#brave_ordering(o22@3, sampled87s21, sampled79s21, <).
#brave_ordering(o23@2, sampled87s22, sampled79s22, <).
#brave_ordering(o24@2, sampled87s23, sampled79s23, <).
#brave_ordering(o25@3, sampled87s24, sampled79s24, <).
#brave_ordering(o26@3, sampled87s25, sampled79s25, <).
#brave_ordering(o27@2, sampled87s26, sampled79s26, <).
#brave_ordering(o28@3, sampled87s27, sampled79s27, <).
#brave_ordering(o29@3, sampled87s28, sampled79s28, <).
#brave_ordering(o30@3, sampled87s29, sampled79s29, <).
#brave_ordering(o31@3, sampled87s30, sampled79s30, <).
#brave_ordering(o32@3, sampled87s31, sampled79s31, <).
#brave_ordering(o33@2, sampled87s32, sampled79s32, <).
#brave_ordering(o34@2, sampled87s33, sampled79s33, <).
#brave_ordering(o35@4, sampled87s34, sampled79s34, <).
#brave_ordering(o36@3, sampled87s35, sampled79s35, <).
#brave_ordering(o37@3, sampled87s36, sampled79s36, <).
#brave_ordering(o38@3, sampled87s37, sampled79s37, <).
#brave_ordering(o39@2, sampled87s38, sampled79s38, <).
#brave_ordering(o40@2, sampled87s39, sampled79s39, <).
#brave_ordering(o41@3, sampled87s40, sampled79s40, <).
#brave_ordering(o42@3, sampled87s41, sampled79s41, <).
#brave_ordering(o43@3, sampled87s42, sampled79s42, <).
#brave_ordering(o44@3, sampled87s43, sampled79s43, <).
#brave_ordering(o45@1, sampled87s44, sampled79s44, <).
