#pos(sampled89s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled89s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,3). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled89s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,3). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled89s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled89s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,1). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled83s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled83s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled83s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@2, sampled89s0, sampled83s0, <).
#brave_ordering(o2@3, sampled89s1, sampled83s1, <).
#brave_ordering(o3@3, sampled89s2, sampled83s2, <).
#brave_ordering(o4@1, sampled89s3, sampled83s3, <).
#brave_ordering(o5@3, sampled89s4, sampled83s4, <).
#brave_ordering(o6@2, sampled89s5, sampled83s5, <).
#brave_ordering(o7@2, sampled89s6, sampled83s6, <).
#brave_ordering(o8@3, sampled89s7, sampled83s7, <).
#brave_ordering(o9@2, sampled89s8, sampled83s8, <).
#brave_ordering(o10@2, sampled89s9, sampled83s9, <).
#brave_ordering(o11@4, sampled89s10, sampled83s10, <).
#brave_ordering(o12@3, sampled89s11, sampled83s11, <).
#brave_ordering(o13@1, sampled89s12, sampled83s12, >).
#brave_ordering(o14@2, sampled89s13, sampled83s13, <).
#brave_ordering(o15@4, sampled89s14, sampled83s14, <).
#brave_ordering(o16@2, sampled89s15, sampled83s15, <).
#brave_ordering(o17@2, sampled89s16, sampled83s16, <).
#brave_ordering(o18@3, sampled89s17, sampled83s17, <).
#brave_ordering(o19@2, sampled89s18, sampled83s18, <).
#brave_ordering(o20@2, sampled89s19, sampled83s19, <).
#brave_ordering(o21@2, sampled89s20, sampled83s20, <).
#brave_ordering(o22@2, sampled89s21, sampled83s21, >).
#brave_ordering(o23@3, sampled89s22, sampled83s22, <).
#brave_ordering(o24@4, sampled89s23, sampled83s23, <).
#brave_ordering(o25@3, sampled89s24, sampled83s24, <).
#brave_ordering(o26@3, sampled89s25, sampled83s25, <).
#brave_ordering(o27@2, sampled89s26, sampled83s26, <).
#brave_ordering(o28@1, sampled89s27, sampled83s27, <).
#brave_ordering(o29@4, sampled89s28, sampled83s28, <).
#brave_ordering(o30@2, sampled89s29, sampled83s29, <).
#brave_ordering(o31@2, sampled89s30, sampled83s30, <).
#brave_ordering(o32@2, sampled89s31, sampled83s31, <).
#brave_ordering(o33@4, sampled89s32, sampled83s32, <).
#brave_ordering(o34@3, sampled89s33, sampled83s33, <).
#brave_ordering(o35@2, sampled89s34, sampled83s34, <).
#brave_ordering(o36@3, sampled89s35, sampled83s35, >).
#brave_ordering(o37@2, sampled89s36, sampled83s36, <).
#brave_ordering(o38@3, sampled89s37, sampled83s37, <).
#brave_ordering(o39@2, sampled89s38, sampled83s38, <).
#brave_ordering(o40@3, sampled89s39, sampled83s39, <).
#brave_ordering(o41@2, sampled89s40, sampled83s40, <).
#brave_ordering(o42@2, sampled89s41, sampled83s41, <).
#brave_ordering(o43@3, sampled89s42, sampled83s42, <).
#brave_ordering(o44@2, sampled89s43, sampled83s43, <).
#brave_ordering(o45@4, sampled89s44, sampled83s44, <).
