#pos(sampled57s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1000). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled57s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3009). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled57s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1000). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled57s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1004). value(frutta,3). value(erbe_spezie_e_condimenti,3004). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1002). value(frutta,3). value(erbe_spezie_e_condimenti,3003). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1001). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1002). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1004). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1001). value(frutta,3). value(erbe_spezie_e_condimenti,3005). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1003). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1003). value(frutta,5). value(erbe_spezie_e_condimenti,3007). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled57s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1004). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1002). value(frutta,3). value(erbe_spezie_e_condimenti,3003). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1001). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled57s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1001). value(frutta,3). value(erbe_spezie_e_condimenti,3004). value(carne,4001). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1000). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled57s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3007). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1003). value(frutta,1). value(erbe_spezie_e_condimenti,3006). value(carne,4000). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1002). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,4000). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1002). value(frutta,2). value(erbe_spezie_e_condimenti,3002). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1002). value(frutta,3). value(erbe_spezie_e_condimenti,3004). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1000). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4001). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1001). value(frutta,1). value(erbe_spezie_e_condimenti,3002). value(carne,4001). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1002). value(frutta,1). value(erbe_spezie_e_condimenti,3003). value(carne,4000). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1008). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled57s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1001). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,4001). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled57s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1003). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled57s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1002). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,4005). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1008). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,6).} ).
#pos(sampled57s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1001). value(frutta,2). value(erbe_spezie_e_condimenti,3001). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled57s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,2). value(erbe_spezie_e_condimenti,3008). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1003). value(frutta,1). value(erbe_spezie_e_condimenti,3007). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,4). value(erbe_spezie_e_condimenti,3004). value(carne,4004). value(funghi_e_tartufi,0). value(pasta,9). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1000). value(frutta,3). value(erbe_spezie_e_condimenti,3002). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled57s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1002). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled57s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,4000). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,1005). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled57s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1002). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1002). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1002). value(frutta,4). value(erbe_spezie_e_condimenti,3007). value(carne,4001). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1008). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled57s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,5). value(erbe_spezie_e_condimenti,3004). value(carne,4002). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled57s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1000). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,4001). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled57s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1003). value(frutta,3). value(erbe_spezie_e_condimenti,3004). value(carne,4003). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2001). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2002). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2001). value(frutta,2). value(erbe_spezie_e_condimenti,1001). value(carne,9001). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,9004). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled48s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1000). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,9001). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2001). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2002). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,9005). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled48s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,9001). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2002). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1000). value(uova,0). value(farinacei,2002). value(frutta,0). value(erbe_spezie_e_condimenti,1004). value(carne,9001). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2002). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,9001). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled48s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled48s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2000). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,9004). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2003). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,9004). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled48s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1005). value(uova,0). value(farinacei,2003). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,9004). value(funghi_e_tartufi,0). value(pasta,9). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,9). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1000). value(uova,0). value(farinacei,2001). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2001). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2004). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,9004). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2004). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled48s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2002). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2005). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled48s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2000). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2004). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,9004). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,1008). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2001). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,9001). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2001). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2002). value(frutta,0). value(erbe_spezie_e_condimenti,1003). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled48s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,9003). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2001). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2001). value(frutta,4). value(erbe_spezie_e_condimenti,1003). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled48s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2004). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2001). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled48s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2001). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,9002). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled48s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2001). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,9000). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled48s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,9000). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@2, sampled57s0, sampled48s0, >).
#brave_ordering(o2@1, sampled57s1, sampled48s1, >).
#brave_ordering(o3@2, sampled57s2, sampled48s2, >).
#brave_ordering(o4@3, sampled57s3, sampled48s3, >).
#brave_ordering(o5@2, sampled57s4, sampled48s4, >).
#brave_ordering(o6@2, sampled57s5, sampled48s5, >).
#brave_ordering(o7@2, sampled57s6, sampled48s6, >).
#brave_ordering(o8@2, sampled57s7, sampled48s7, >).
#brave_ordering(o9@1, sampled57s8, sampled48s8, >).
#brave_ordering(o10@2, sampled57s9, sampled48s9, >).
#brave_ordering(o11@2, sampled57s10, sampled48s10, >).
#brave_ordering(o12@2, sampled57s11, sampled48s11, >).
#brave_ordering(o13@3, sampled57s12, sampled48s12, >).
#brave_ordering(o14@2, sampled57s13, sampled48s13, >).
#brave_ordering(o15@2, sampled57s14, sampled48s14, >).
#brave_ordering(o16@1, sampled57s15, sampled48s15, >).
#brave_ordering(o17@2, sampled57s16, sampled48s16, >).
#brave_ordering(o18@1, sampled57s17, sampled48s17, >).
#brave_ordering(o19@2, sampled57s18, sampled48s18, >).
#brave_ordering(o20@1, sampled57s19, sampled48s19, >).
#brave_ordering(o21@2, sampled57s20, sampled48s20, >).
#brave_ordering(o22@2, sampled57s21, sampled48s21, >).
#brave_ordering(o23@2, sampled57s22, sampled48s22, >).
#brave_ordering(o24@2, sampled57s23, sampled48s23, >).
#brave_ordering(o25@2, sampled57s24, sampled48s24, >).
#brave_ordering(o26@2, sampled57s25, sampled48s25, >).
#brave_ordering(o27@1, sampled57s26, sampled48s26, >).
#brave_ordering(o28@2, sampled57s27, sampled48s27, >).
#brave_ordering(o29@1, sampled57s28, sampled48s28, >).
#brave_ordering(o30@1, sampled57s29, sampled48s29, >).
#brave_ordering(o31@1, sampled57s30, sampled48s30, >).
#brave_ordering(o32@1, sampled57s31, sampled48s31, >).
#brave_ordering(o33@2, sampled57s32, sampled48s32, >).
#brave_ordering(o34@2, sampled57s33, sampled48s33, >).
#brave_ordering(o35@2, sampled57s34, sampled48s34, >).
#brave_ordering(o36@2, sampled57s35, sampled48s35, >).
#brave_ordering(o37@2, sampled57s36, sampled48s36, >).
#brave_ordering(o38@2, sampled57s37, sampled48s37, >).
#brave_ordering(o39@2, sampled57s38, sampled48s38, >).
#brave_ordering(o40@2, sampled57s39, sampled48s39, >).
#brave_ordering(o41@2, sampled57s40, sampled48s40, >).
#brave_ordering(o42@2, sampled57s41, sampled48s41, >).
#brave_ordering(o43@2, sampled57s42, sampled48s42, >).
#brave_ordering(o44@3, sampled57s43, sampled48s43, >).
#brave_ordering(o45@3, sampled57s44, sampled48s44, >).
