#pos(sampled49s0, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2000). value(frutta,1). value(erbe_spezie_e_condimenti,2). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s1, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,2). value(carne,0). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled49s2, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,5004). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s3, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s4, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,5). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled49s5, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,5). value(carne,2). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled49s6, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,3). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s7, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,4). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s8, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2004). value(frutta,2). value(erbe_spezie_e_condimenti,6). value(carne,3). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,6).} ).
#pos(sampled49s9, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,2). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s10, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2002). value(frutta,1). value(erbe_spezie_e_condimenti,2). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s11, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2004). value(frutta,1). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5000). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s12, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2000). value(frutta,0). value(erbe_spezie_e_condimenti,3). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s13, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,2). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s14, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2005). value(frutta,5). value(erbe_spezie_e_condimenti,7). value(carne,4). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s15, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,8). value(carne,4). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled49s16, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2000). value(frutta,1). value(erbe_spezie_e_condimenti,3). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5000). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s17, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2005). value(frutta,3). value(erbe_spezie_e_condimenti,7). value(carne,2). value(funghi_e_tartufi,0). value(pasta,9). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s18, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,0). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s19, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2002). value(frutta,1). value(erbe_spezie_e_condimenti,6). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,5005). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s20, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,8). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s21, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,5). value(carne,4). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s22, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,1). value(carne,5). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s23, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2002). value(frutta,4). value(erbe_spezie_e_condimenti,6). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s24, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2003). value(frutta,4). value(erbe_spezie_e_condimenti,6). value(carne,4). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s25, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s26, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s27, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2004). value(frutta,4). value(erbe_spezie_e_condimenti,9). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5004). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s28, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,1). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s29, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2003). value(frutta,3). value(erbe_spezie_e_condimenti,6). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s30, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2001). value(frutta,3). value(erbe_spezie_e_condimenti,1). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s31, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2002). value(frutta,5). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s32, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2001). value(frutta,3). value(erbe_spezie_e_condimenti,5). value(carne,2). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled49s33, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2001). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5004). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s34, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2002). value(frutta,0). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s35, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2002). value(frutta,1). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5000). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled49s36, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2001). value(frutta,2). value(erbe_spezie_e_condimenti,1). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s37, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2003). value(frutta,1). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5004). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s38, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled49s39, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2003). value(frutta,2). value(erbe_spezie_e_condimenti,5). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5001). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s40, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2004). value(frutta,5). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s41, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2002). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,1). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled49s42, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2001). value(frutta,2). value(erbe_spezie_e_condimenti,5). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,5000). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled49s43, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2004). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5002). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled49s44, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2002). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,5003). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4000). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3002). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled6s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4000). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4001). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4001). value(marinatura,0). value(mantecatura,0). value(forno,4004). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3002). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4000). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4000). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3008). value(bollitura,0). value(rosolatura,0). value(frittura,4000). value(marinatura,0). value(mantecatura,0). value(forno,4004). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4004). value(marinatura,0). value(mantecatura,0). value(forno,4004). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled6s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled6s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled6s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3002). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1008). value(carne,5). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,4004). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled6s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,6). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3007). value(bollitura,0). value(rosolatura,0). value(frittura,4004). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3007). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4004). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled6s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4004). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4001). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4001). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3002). value(bollitura,0). value(rosolatura,0). value(frittura,4001). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,5). value(erbe_spezie_e_condimenti,1007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled6s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4001). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1001). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled6s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1009). value(carne,0). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4003). value(marinatura,0). value(mantecatura,0). value(forno,4004). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled6s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4004). value(marinatura,0). value(mantecatura,0). value(forno,4001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled6s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4002). value(marinatura,0). value(mantecatura,0). value(forno,4003). value(cottura_a_fiamma,0). value(stufato,4).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@3, sampled49s0, sampled6s0, <).
#brave_ordering(o2@3, sampled49s1, sampled6s1, <).
#brave_ordering(o3@2, sampled49s2, sampled6s2, <).
#brave_ordering(o4@3, sampled49s3, sampled6s3, <).
#brave_ordering(o5@3, sampled49s4, sampled6s4, <).
#brave_ordering(o6@3, sampled49s5, sampled6s5, <).
#brave_ordering(o7@3, sampled49s6, sampled6s6, <).
#brave_ordering(o8@2, sampled49s7, sampled6s7, <).
#brave_ordering(o9@2, sampled49s8, sampled6s8, <).
#brave_ordering(o10@3, sampled49s9, sampled6s9, <).
#brave_ordering(o11@4, sampled49s10, sampled6s10, <).
#brave_ordering(o12@3, sampled49s11, sampled6s11, <).
#brave_ordering(o13@2, sampled49s12, sampled6s12, <).
#brave_ordering(o14@3, sampled49s13, sampled6s13, <).
#brave_ordering(o15@2, sampled49s14, sampled6s14, <).
#brave_ordering(o16@2, sampled49s15, sampled6s15, <).
#brave_ordering(o17@3, sampled49s16, sampled6s16, <).
#brave_ordering(o18@2, sampled49s17, sampled6s17, <).
#brave_ordering(o19@3, sampled49s18, sampled6s18, <).
#brave_ordering(o20@2, sampled49s19, sampled6s19, <).
#brave_ordering(o21@3, sampled49s20, sampled6s20, <).
#brave_ordering(o22@2, sampled49s21, sampled6s21, <).
#brave_ordering(o23@2, sampled49s22, sampled6s22, <).
#brave_ordering(o24@2, sampled49s23, sampled6s23, <).
#brave_ordering(o25@2, sampled49s24, sampled6s24, <).
#brave_ordering(o26@3, sampled49s25, sampled6s25, <).
#brave_ordering(o27@3, sampled49s26, sampled6s26, <).
#brave_ordering(o28@1, sampled49s27, sampled6s27, <).
#brave_ordering(o29@3, sampled49s28, sampled6s28, <).
#brave_ordering(o30@2, sampled49s29, sampled6s29, <).
#brave_ordering(o31@3, sampled49s30, sampled6s30, <).
#brave_ordering(o32@3, sampled49s31, sampled6s31, <).
#brave_ordering(o33@3, sampled49s32, sampled6s32, <).
#brave_ordering(o34@2, sampled49s33, sampled6s33, <).
#brave_ordering(o35@3, sampled49s34, sampled6s34, <).
#brave_ordering(o36@3, sampled49s35, sampled6s35, <).
#brave_ordering(o37@4, sampled49s36, sampled6s36, <).
#brave_ordering(o38@2, sampled49s37, sampled6s37, <).
#brave_ordering(o39@3, sampled49s38, sampled6s38, <).
#brave_ordering(o40@3, sampled49s39, sampled6s39, <).
#brave_ordering(o41@2, sampled49s40, sampled6s40, <).
#brave_ordering(o42@3, sampled49s41, sampled6s41, <).
#brave_ordering(o43@2, sampled49s42, sampled6s42, <).
#brave_ordering(o44@3, sampled49s43, sampled6s43, <).
#brave_ordering(o45@2, sampled49s44, sampled6s44, <).
