#pos(sampled89s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,2). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,3). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled89s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s39, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled89s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled36s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,7). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s1, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s3, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,5). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s7, {}, {}, {category(2). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,1). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,1). value(funghi_e_tartufi,3). value(pasta,3). value(pesce,3). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,1). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled36s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,1). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,2). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,1). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,3). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,7). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,1). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled36s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,8). value(carne,0). value(funghi_e_tartufi,3). value(pasta,4). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@4, sampled89s0, sampled36s0, >).
#brave_ordering(o2@3, sampled89s1, sampled36s1, <).
#brave_ordering(o3@3, sampled89s2, sampled36s2, >).
#brave_ordering(o4@3, sampled89s3, sampled36s3, <).
#brave_ordering(o5@3, sampled89s4, sampled36s4, >).
#brave_ordering(o6@3, sampled89s5, sampled36s5, >).
#brave_ordering(o7@4, sampled89s6, sampled36s6, >).
#brave_ordering(o8@3, sampled89s8, sampled36s8, >).
#brave_ordering(o9@2, sampled89s9, sampled36s9, <).
#brave_ordering(o10@4, sampled89s10, sampled36s10, >).
#brave_ordering(o11@3, sampled89s11, sampled36s11, >).
#brave_ordering(o12@3, sampled89s12, sampled36s12, >).
#brave_ordering(o13@4, sampled89s13, sampled36s13, >).
#brave_ordering(o14@3, sampled89s14, sampled36s14, >).
#brave_ordering(o15@3, sampled89s15, sampled36s15, >).
#brave_ordering(o16@4, sampled89s16, sampled36s16, <).
#brave_ordering(o17@2, sampled89s17, sampled36s17, >).
#brave_ordering(o18@4, sampled89s18, sampled36s18, >).
#brave_ordering(o19@3, sampled89s19, sampled36s19, >).
#brave_ordering(o20@3, sampled89s20, sampled36s20, >).
#brave_ordering(o21@5, sampled89s21, sampled36s21, >).
#brave_ordering(o22@3, sampled89s22, sampled36s22, <).
#brave_ordering(o23@3, sampled89s23, sampled36s23, <).
#brave_ordering(o24@4, sampled89s24, sampled36s24, >).
#brave_ordering(o25@3, sampled89s25, sampled36s25, <).
#brave_ordering(o26@3, sampled89s26, sampled36s26, >).
#brave_ordering(o27@5, sampled89s27, sampled36s27, >).
#brave_ordering(o28@4, sampled89s28, sampled36s28, >).
#brave_ordering(o29@3, sampled89s29, sampled36s29, >).
#brave_ordering(o30@1, sampled89s30, sampled36s30, >).
#brave_ordering(o31@3, sampled89s31, sampled36s31, >).
#brave_ordering(o32@4, sampled89s32, sampled36s32, >).
#brave_ordering(o33@4, sampled89s33, sampled36s33, >).
#brave_ordering(o34@4, sampled89s34, sampled36s34, >).
#brave_ordering(o35@5, sampled89s35, sampled36s35, >).
#brave_ordering(o36@4, sampled89s36, sampled36s36, >).
#brave_ordering(o37@4, sampled89s37, sampled36s37, >).
#brave_ordering(o38@4, sampled89s38, sampled36s38, >).
#brave_ordering(o39@2, sampled89s39, sampled36s39, >).
#brave_ordering(o40@5, sampled89s40, sampled36s40, >).
#brave_ordering(o41@3, sampled89s41, sampled36s41, >).
#brave_ordering(o42@3, sampled89s42, sampled36s42, >).
#brave_ordering(o43@4, sampled89s43, sampled36s43, >).
#brave_ordering(o44@3, sampled89s44, sampled36s44, >).
