#pos(sampled51s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4002). value(frutta,4). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4003). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4002). value(frutta,0). value(erbe_spezie_e_condimenti,3). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4003). value(frutta,4). value(erbe_spezie_e_condimenti,5). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4004). value(frutta,2). value(erbe_spezie_e_condimenti,3). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4003). value(frutta,4). value(erbe_spezie_e_condimenti,5). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4003). value(frutta,1). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4000). value(frutta,4). value(erbe_spezie_e_condimenti,4). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4004). value(frutta,4). value(erbe_spezie_e_condimenti,6). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4002). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,2). value(erbe_spezie_e_condimenti,6). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled51s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4004). value(frutta,2). value(erbe_spezie_e_condimenti,3). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4004). value(frutta,3). value(erbe_spezie_e_condimenti,6). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4004). value(frutta,1). value(erbe_spezie_e_condimenti,7). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,2). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4004). value(frutta,3). value(erbe_spezie_e_condimenti,2). value(carne,3). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4001). value(frutta,0). value(erbe_spezie_e_condimenti,5). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4003). value(frutta,0). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4003). value(frutta,3). value(erbe_spezie_e_condimenti,6). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,2). value(erbe_spezie_e_condimenti,7). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4000). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4003). value(frutta,3). value(erbe_spezie_e_condimenti,6). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4001). value(frutta,1). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,1). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4002). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,0). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,1). value(erbe_spezie_e_condimenti,6). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled51s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4001). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4004). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4003). value(frutta,3). value(erbe_spezie_e_condimenti,1). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4002). value(frutta,1). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4003). value(frutta,3). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4002). value(frutta,4). value(erbe_spezie_e_condimenti,5). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled51s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4001). value(frutta,3). value(erbe_spezie_e_condimenti,5). value(carne,4). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4001). value(frutta,1). value(erbe_spezie_e_condimenti,5). value(carne,3). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4002). value(frutta,4). value(erbe_spezie_e_condimenti,6). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4003). value(frutta,3). value(erbe_spezie_e_condimenti,3). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4004). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4003). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4001). value(frutta,2). value(erbe_spezie_e_condimenti,4). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled51s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4000). value(frutta,2). value(erbe_spezie_e_condimenti,2). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled51s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4003). value(frutta,2). value(erbe_spezie_e_condimenti,8). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled51s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4004). value(frutta,2). value(erbe_spezie_e_condimenti,5). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4002). value(frutta,5). value(erbe_spezie_e_condimenti,1). value(carne,2). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled51s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4003). value(frutta,0). value(erbe_spezie_e_condimenti,6). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1009). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled5s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled5s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1000). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,5004). value(funghi_e_tartufi,0). value(pasta,4007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled5s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1002). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,5005). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,5). value(erbe_spezie_e_condimenti,1005). value(carne,5005). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5008). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,5001). value(funghi_e_tartufi,0). value(pasta,4002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,5004). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5000). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,5001). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5000). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled5s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,5001). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5000). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1006). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled5s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4001). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,5000). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,5001). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5000). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,1). value(frutta,5). value(erbe_spezie_e_condimenti,1005). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5008). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5008). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,1007). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled5s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1001). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1005). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5008). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,5005). value(funghi_e_tartufi,0). value(pasta,4007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5008). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled5s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1001). value(carne,5000). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5004). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1005). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5003). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1003). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled5s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1003). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1003). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1004). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,5003). value(funghi_e_tartufi,0). value(pasta,4006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled5s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5002). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,5001). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled5s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1002). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1004). value(carne,5002). value(funghi_e_tartufi,0). value(pasta,4005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5002). value(cottura_a_fiamma,0). value(stufato,3).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@2, sampled51s0, sampled5s0, =).
#brave_ordering(o2@2, sampled51s1, sampled5s1, =).
#brave_ordering(o3@4, sampled51s2, sampled5s2, =).
#brave_ordering(o4@2, sampled51s3, sampled5s3, =).
#brave_ordering(o5@3, sampled51s4, sampled5s4, =).
#brave_ordering(o6@2, sampled51s5, sampled5s5, =).
#brave_ordering(o7@2, sampled51s6, sampled5s6, =).
#brave_ordering(o8@3, sampled51s7, sampled5s7, =).
#brave_ordering(o9@1, sampled51s8, sampled5s8, =).
#brave_ordering(o10@2, sampled51s9, sampled5s9, =).
#brave_ordering(o11@3, sampled51s10, sampled5s10, =).
#brave_ordering(o12@2, sampled51s11, sampled5s11, =).
#brave_ordering(o13@2, sampled51s12, sampled5s12, =).
#brave_ordering(o14@2, sampled51s13, sampled5s13, =).
#brave_ordering(o15@2, sampled51s14, sampled5s14, =).
#brave_ordering(o16@2, sampled51s15, sampled5s15, =).
#brave_ordering(o17@3, sampled51s16, sampled5s16, =).
#brave_ordering(o18@3, sampled51s17, sampled5s17, =).
#brave_ordering(o19@3, sampled51s18, sampled5s18, =).
#brave_ordering(o20@2, sampled51s19, sampled5s19, =).
#brave_ordering(o21@3, sampled51s20, sampled5s20, =).
#brave_ordering(o22@3, sampled51s21, sampled5s21, =).
#brave_ordering(o23@3, sampled51s22, sampled5s22, =).
#brave_ordering(o24@3, sampled51s23, sampled5s23, =).
#brave_ordering(o25@3, sampled51s24, sampled5s24, =).
#brave_ordering(o26@2, sampled51s25, sampled5s25, =).
#brave_ordering(o27@3, sampled51s26, sampled5s26, =).
#brave_ordering(o28@2, sampled51s27, sampled5s27, =).
#brave_ordering(o29@1, sampled51s28, sampled5s28, =).
#brave_ordering(o30@3, sampled51s29, sampled5s29, =).
#brave_ordering(o31@2, sampled51s30, sampled5s30, =).
#brave_ordering(o32@3, sampled51s31, sampled5s31, =).
#brave_ordering(o33@2, sampled51s32, sampled5s32, =).
#brave_ordering(o34@2, sampled51s33, sampled5s33, =).
#brave_ordering(o35@2, sampled51s34, sampled5s34, =).
#brave_ordering(o36@2, sampled51s35, sampled5s35, =).
#brave_ordering(o37@3, sampled51s36, sampled5s36, =).
#brave_ordering(o38@3, sampled51s37, sampled5s37, =).
#brave_ordering(o39@3, sampled51s38, sampled5s38, =).
#brave_ordering(o40@2, sampled51s39, sampled5s39, =).
#brave_ordering(o41@3, sampled51s40, sampled5s40, =).
#brave_ordering(o42@2, sampled51s41, sampled5s41, =).
#brave_ordering(o43@2, sampled51s42, sampled5s42, =).
#brave_ordering(o44@3, sampled51s43, sampled5s43, =).
#brave_ordering(o45@2, sampled51s44, sampled5s44, =).
