#pos(sampled54s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8002). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled54s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled54s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,3003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8001). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,3006). value(carne,4). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8001). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled54s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled54s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,3008). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3002). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,3003). value(carne,4). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,0). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8007). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled54s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8009). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8001). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3005). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,3002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3002). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled54s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,3003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled54s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,3003). value(carne,4). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled54s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,3001). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,8003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3002). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3008). value(carne,3). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled22s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6001). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled22s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled22s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,6). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6001). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled22s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,3007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s17, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,3007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled22s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s20, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,0). value(frutta,4). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled22s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,3006). value(carne,4). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled22s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,3005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6008). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled22s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6008). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6002). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3003). value(carne,0). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled22s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled22s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled22s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,3002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,3007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,3005). value(carne,0). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled22s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,3002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled22s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,3005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,0).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@1, sampled54s0, sampled22s0, <).
#brave_ordering(o2@1, sampled54s1, sampled22s1, <).
#brave_ordering(o3@1, sampled54s2, sampled22s2, <).
#brave_ordering(o4@2, sampled54s3, sampled22s3, <).
#brave_ordering(o5@2, sampled54s4, sampled22s4, <).
#brave_ordering(o6@1, sampled54s5, sampled22s5, <).
#brave_ordering(o7@2, sampled54s6, sampled22s6, <).
#brave_ordering(o8@2, sampled54s7, sampled22s7, <).
#brave_ordering(o9@2, sampled54s8, sampled22s8, <).
#brave_ordering(o10@2, sampled54s9, sampled22s9, <).
#brave_ordering(o11@2, sampled54s10, sampled22s10, <).
#brave_ordering(o12@1, sampled54s11, sampled22s11, <).
#brave_ordering(o13@2, sampled54s12, sampled22s12, <).
#brave_ordering(o14@2, sampled54s13, sampled22s13, <).
#brave_ordering(o15@1, sampled54s14, sampled22s14, <).
#brave_ordering(o16@1, sampled54s15, sampled22s15, <).
#brave_ordering(o17@2, sampled54s16, sampled22s16, <).
#brave_ordering(o18@1, sampled54s17, sampled22s17, <).
#brave_ordering(o19@1, sampled54s18, sampled22s18, <).
#brave_ordering(o20@2, sampled54s19, sampled22s19, <).
#brave_ordering(o21@2, sampled54s20, sampled22s20, <).
#brave_ordering(o22@1, sampled54s21, sampled22s21, <).
#brave_ordering(o23@1, sampled54s22, sampled22s22, <).
#brave_ordering(o24@1, sampled54s23, sampled22s23, <).
#brave_ordering(o25@1, sampled54s24, sampled22s24, <).
#brave_ordering(o26@1, sampled54s25, sampled22s25, <).
#brave_ordering(o27@2, sampled54s26, sampled22s26, <).
#brave_ordering(o28@2, sampled54s27, sampled22s27, <).
#brave_ordering(o29@1, sampled54s28, sampled22s28, <).
#brave_ordering(o30@2, sampled54s29, sampled22s29, <).
#brave_ordering(o31@1, sampled54s30, sampled22s30, <).
#brave_ordering(o32@1, sampled54s31, sampled22s31, <).
#brave_ordering(o33@2, sampled54s32, sampled22s32, <).
#brave_ordering(o34@1, sampled54s33, sampled22s33, <).
#brave_ordering(o35@2, sampled54s34, sampled22s34, <).
#brave_ordering(o36@2, sampled54s35, sampled22s35, <).
#brave_ordering(o37@1, sampled54s36, sampled22s36, <).
#brave_ordering(o38@2, sampled54s37, sampled22s37, <).
#brave_ordering(o39@2, sampled54s38, sampled22s38, <).
#brave_ordering(o40@2, sampled54s39, sampled22s39, <).
#brave_ordering(o41@2, sampled54s40, sampled22s40, <).
#brave_ordering(o42@1, sampled54s41, sampled22s41, <).
#brave_ordering(o43@1, sampled54s42, sampled22s42, <).
#brave_ordering(o44@2, sampled54s43, sampled22s43, <).
#brave_ordering(o45@2, sampled54s44, sampled22s44, <).
