#pos(sampled39s0, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2003). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s1, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2003). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s2, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2003). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2002). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled39s3, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,2003). value(erbe_spezie_e_condimenti,3003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s4, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,2004). value(erbe_spezie_e_condimenti,3004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2002). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s5, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,2002). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2001). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s6, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2002). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s7, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2001). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s8, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2003). value(erbe_spezie_e_condimenti,3006). value(carne,4). value(funghi_e_tartufi,0). value(pasta,10). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2008). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s9, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2000). value(erbe_spezie_e_condimenti,3002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2001). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s10, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2000). value(erbe_spezie_e_condimenti,3003). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s11, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,2002). value(erbe_spezie_e_condimenti,3004). value(carne,5). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s12, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,2003). value(erbe_spezie_e_condimenti,3007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s13, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2001). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s14, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2001). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s15, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2000). value(erbe_spezie_e_condimenti,3002). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s16, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2003). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s17, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2003). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,9). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s18, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2002). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s19, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2001). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled39s20, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2002). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s21, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2002). value(erbe_spezie_e_condimenti,3005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s22, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,2004). value(erbe_spezie_e_condimenti,3003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s23, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2001). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s24, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2003). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s25, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2001). value(erbe_spezie_e_condimenti,3009). value(carne,4). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s26, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2003). value(erbe_spezie_e_condimenti,3002). value(carne,2). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s27, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2004). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s28, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2001). value(erbe_spezie_e_condimenti,3006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s29, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2003). value(erbe_spezie_e_condimenti,3008). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s30, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2002). value(erbe_spezie_e_condimenti,3004). value(carne,0). value(funghi_e_tartufi,0). value(pasta,8). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s31, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2002). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2007). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s32, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2003). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s33, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,2001). value(erbe_spezie_e_condimenti,3001). value(carne,2). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s34, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2002). value(erbe_spezie_e_condimenti,3005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s35, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2002). value(erbe_spezie_e_condimenti,3006). value(carne,3). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s36, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2002). value(erbe_spezie_e_condimenti,3004). value(carne,4). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled39s37, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2000). value(erbe_spezie_e_condimenti,3004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled39s38, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2002). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s39, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2002). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled39s40, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,2001). value(erbe_spezie_e_condimenti,3002). value(carne,1). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s41, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2002). value(erbe_spezie_e_condimenti,3005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,7). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2008). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s42, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2001). value(erbe_spezie_e_condimenti,3005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,6). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled39s43, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,2004). value(erbe_spezie_e_condimenti,3006). value(carne,4). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled39s44, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2003). value(erbe_spezie_e_condimenti,3004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3002). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1006). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1006). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,0). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,1008). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1001). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3008). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1002). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1002). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,5). value(erbe_spezie_e_condimenti,1005). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,1006). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1001). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5002). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3008). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,5). value(erbe_spezie_e_condimenti,1007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled37s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,1005). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,0). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,5). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled37s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1005). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1003). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1006). value(carne,5). value(funghi_e_tartufi,0). value(pasta,5007). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1001). value(carne,0). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled37s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,1007). value(carne,4). value(funghi_e_tartufi,0). value(pasta,5008). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3007). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled37s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,5). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled37s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,1003). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3004). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,1007). value(carne,2). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3006). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5005). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3001). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled37s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,1006). value(carne,1). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3005). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5004). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3003). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled37s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,1004). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5003). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3001). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled37s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,1007). value(carne,3). value(funghi_e_tartufi,0). value(pasta,5006). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3007). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@4, sampled39s0, sampled37s0, >).
#brave_ordering(o2@4, sampled39s1, sampled37s1, >).
#brave_ordering(o3@3, sampled39s2, sampled37s2, >).
#brave_ordering(o4@3, sampled39s3, sampled37s3, >).
#brave_ordering(o5@3, sampled39s4, sampled37s4, >).
#brave_ordering(o6@4, sampled39s5, sampled37s5, >).
#brave_ordering(o7@3, sampled39s6, sampled37s6, >).
#brave_ordering(o8@2, sampled39s7, sampled37s7, >).
#brave_ordering(o9@4, sampled39s8, sampled37s8, >).
#brave_ordering(o10@3, sampled39s9, sampled37s9, >).
#brave_ordering(o11@3, sampled39s10, sampled37s10, >).
#brave_ordering(o12@4, sampled39s11, sampled37s11, >).
#brave_ordering(o13@3, sampled39s12, sampled37s12, >).
#brave_ordering(o14@4, sampled39s13, sampled37s13, >).
#brave_ordering(o15@2, sampled39s14, sampled37s14, >).
#brave_ordering(o16@4, sampled39s15, sampled37s15, >).
#brave_ordering(o17@3, sampled39s16, sampled37s16, >).
#brave_ordering(o18@3, sampled39s17, sampled37s17, >).
#brave_ordering(o19@3, sampled39s18, sampled37s18, >).
#brave_ordering(o20@3, sampled39s19, sampled37s19, >).
#brave_ordering(o21@2, sampled39s20, sampled37s20, >).
#brave_ordering(o22@3, sampled39s21, sampled37s21, >).
#brave_ordering(o23@4, sampled39s22, sampled37s22, >).
#brave_ordering(o24@3, sampled39s23, sampled37s23, >).
#brave_ordering(o25@2, sampled39s24, sampled37s24, >).
#brave_ordering(o26@2, sampled39s25, sampled37s25, >).
#brave_ordering(o27@4, sampled39s26, sampled37s26, >).
#brave_ordering(o28@3, sampled39s27, sampled37s27, >).
#brave_ordering(o29@2, sampled39s28, sampled37s28, >).
#brave_ordering(o30@2, sampled39s29, sampled37s29, >).
#brave_ordering(o31@3, sampled39s30, sampled37s30, >).
#brave_ordering(o32@3, sampled39s31, sampled37s31, >).
#brave_ordering(o33@2, sampled39s32, sampled37s32, >).
#brave_ordering(o34@4, sampled39s33, sampled37s33, >).
#brave_ordering(o35@1, sampled39s34, sampled37s34, >).
#brave_ordering(o36@2, sampled39s35, sampled37s35, >).
#brave_ordering(o37@2, sampled39s36, sampled37s36, >).
#brave_ordering(o38@3, sampled39s37, sampled37s37, >).
#brave_ordering(o39@3, sampled39s38, sampled37s38, >).
#brave_ordering(o40@3, sampled39s39, sampled37s39, >).
#brave_ordering(o41@4, sampled39s40, sampled37s40, >).
#brave_ordering(o42@3, sampled39s41, sampled37s41, >).
#brave_ordering(o43@3, sampled39s42, sampled37s42, >).
#brave_ordering(o44@4, sampled39s43, sampled37s43, >).
#brave_ordering(o45@2, sampled39s44, sampled37s44, >).
