#pos(sampled10s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,1). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,6). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,1). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled10s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,5). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,3). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,6). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s27, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,4). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,11). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled10s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,11). value(carne,1). value(funghi_e_tartufi,3). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,9). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled10s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,11). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled10s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,0). value(funghi_e_tartufi,4). value(pasta,5). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled15s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s5, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled15s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,3). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,1). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled15s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@2, sampled10s5, sampled15s5, >).
#brave_ordering(o2@2, sampled10s8, sampled15s8, <).
#brave_ordering(o3@3, sampled10s10, sampled15s10, >).
#brave_ordering(o4@2, sampled10s13, sampled15s13, <).
#brave_ordering(o5@3, sampled10s17, sampled15s17, >).
#brave_ordering(o6@2, sampled10s19, sampled15s19, <).
#brave_ordering(o7@1, sampled10s27, sampled15s27, <).
#brave_ordering(o8@2, sampled10s28, sampled15s28, <).
#brave_ordering(o9@2, sampled10s41, sampled15s41, >).
