#pos(sampled57s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,6).} ).
#pos(sampled57s4, {}, {}, {category(2). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled57s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s15, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s16, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s17, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,1). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,3). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,1). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,6).} ).
#pos(sampled57s22, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,3). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s25, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,1). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,1). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled57s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s34, {}, {}, {category(2). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,5). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,2). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,2). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,4). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled57s44, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,3). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled86s0, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s1, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s2, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s3, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s4, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s5, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s6, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s7, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s8, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s9, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s10, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled86s11, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s12, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s13, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s14, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s15, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s16, {}, {}, {category(2). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s18, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s19, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s20, {}, {}, {category(2). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s21, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled86s22, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s23, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,3). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s24, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s25, {}, {}, {category(2). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s26, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s27, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s28, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s29, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s30, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s31, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s32, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s33, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s34, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s35, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s36, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s37, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s38, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,1). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s39, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,2). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s40, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,1). value(carne,0). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s41, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s42, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,1). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s43, {}, {}, {category(4). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,0). value(carne,1). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled86s44, {}, {}, {category(1). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,0). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,1). value(dolcificanti,0). value(verdure_e_ortaggi,0). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@3, sampled57s4, sampled86s4, <).
#brave_ordering(o2@3, sampled57s16, sampled86s16, >).
#brave_ordering(o3@1, sampled57s17, sampled86s17, <).
#brave_ordering(o4@1, sampled57s20, sampled86s20, >).
#brave_ordering(o5@2, sampled57s25, sampled86s25, >).
#brave_ordering(o6@2, sampled57s34, sampled86s34, <).
#brave_ordering(o7@4, sampled57s38, sampled86s38, >).
