#pos(sampled81s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,0). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,301). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,301). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,0). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,105). value(carne,4). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,103). value(carne,1). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,103). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,4). value(erbe_spezie_e_condimenti,102). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,4). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,107). value(carne,0). value(funghi_e_tartufi,0). value(pasta,510). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled81s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,301). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,0). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,5). value(frutta,4). value(erbe_spezie_e_condimenti,107). value(carne,4). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,104). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,107). value(carne,1). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,101). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,108). value(carne,1). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,108). value(carne,5). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,109). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,108). value(carne,4). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,108). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled55s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,1). value(erbe_spezie_e_condimenti,106). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled55s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,106). value(carne,1). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,104). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled55s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,102). value(carne,4). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,5). value(frutta,4). value(erbe_spezie_e_condimenti,104). value(carne,4). value(funghi_e_tartufi,0). value(pasta,510). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,108). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,5).} ).
#pos(sampled55s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,107). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,4). value(funghi_e_tartufi,0). value(pasta,509). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,104). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled55s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled55s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,3). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,107). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,5). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,109). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,107). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,107). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,0). value(frutta,5). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,104). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,102). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled55s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,102). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,107). value(carne,1). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,102). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,5). value(erbe_spezie_e_condimenti,107). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,4). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,0). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,103). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,105). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled55s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,107). value(carne,4). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,104). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled55s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,104). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled55s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,107). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,106). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled55s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,102). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled55s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,108). value(carne,3). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,108). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@3, sampled81s0, sampled55s0, <).
#brave_ordering(o2@2, sampled81s1, sampled55s1, <).
#brave_ordering(o3@4, sampled81s2, sampled55s2, <).
#brave_ordering(o4@3, sampled81s3, sampled55s3, <).
#brave_ordering(o5@3, sampled81s4, sampled55s4, <).
#brave_ordering(o6@4, sampled81s5, sampled55s5, >).
#brave_ordering(o7@3, sampled81s6, sampled55s6, <).
#brave_ordering(o8@3, sampled81s7, sampled55s7, <).
#brave_ordering(o9@1, sampled81s8, sampled55s8, <).
#brave_ordering(o10@2, sampled81s9, sampled55s9, <).
#brave_ordering(o11@4, sampled81s10, sampled55s10, <).
#brave_ordering(o12@2, sampled81s11, sampled55s11, <).
#brave_ordering(o13@4, sampled81s12, sampled55s12, <).
#brave_ordering(o14@4, sampled81s13, sampled55s13, <).
#brave_ordering(o15@3, sampled81s14, sampled55s14, <).
#brave_ordering(o16@4, sampled81s15, sampled55s15, >).
#brave_ordering(o17@4, sampled81s16, sampled55s16, <).
#brave_ordering(o18@2, sampled81s17, sampled55s17, <).
#brave_ordering(o19@3, sampled81s18, sampled55s18, <).
#brave_ordering(o20@2, sampled81s19, sampled55s19, <).
#brave_ordering(o21@3, sampled81s20, sampled55s20, <).
#brave_ordering(o22@3, sampled81s21, sampled55s21, <).
#brave_ordering(o23@4, sampled81s22, sampled55s22, <).
#brave_ordering(o24@2, sampled81s23, sampled55s23, <).
#brave_ordering(o25@1, sampled81s24, sampled55s24, <).
#brave_ordering(o26@3, sampled81s25, sampled55s25, <).
#brave_ordering(o27@3, sampled81s26, sampled55s26, <).
#brave_ordering(o28@3, sampled81s27, sampled55s27, <).
#brave_ordering(o29@3, sampled81s28, sampled55s28, <).
#brave_ordering(o30@4, sampled81s29, sampled55s29, >).
#brave_ordering(o31@3, sampled81s30, sampled55s30, <).
#brave_ordering(o32@4, sampled81s31, sampled55s31, <).
#brave_ordering(o33@3, sampled81s32, sampled55s32, <).
#brave_ordering(o34@3, sampled81s33, sampled55s33, <).
#brave_ordering(o35@3, sampled81s34, sampled55s34, <).
#brave_ordering(o36@3, sampled81s35, sampled55s35, <).
#brave_ordering(o37@3, sampled81s36, sampled55s36, <).
#brave_ordering(o38@3, sampled81s37, sampled55s37, >).
#brave_ordering(o39@5, sampled81s38, sampled55s38, <).
#brave_ordering(o40@3, sampled81s39, sampled55s39, <).
#brave_ordering(o41@3, sampled81s40, sampled55s40, <).
#brave_ordering(o42@5, sampled81s41, sampled55s41, <).
#brave_ordering(o43@3, sampled81s42, sampled55s42, >).
#brave_ordering(o44@3, sampled81s43, sampled55s43, <).
#brave_ordering(o45@2, sampled81s44, sampled55s44, <).
