#pos(sampled81s0, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,107). value(carne,4). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s1, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,5). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s2, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,500). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s3, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,101). value(carne,2). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s4, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s5, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s6, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,309). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s7, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s8, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s9, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,107). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s10, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,102). value(carne,4). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled81s11, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,4). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s12, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,106). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s13, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,5). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s14, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,104). value(carne,1). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s15, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,5). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s16, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,107). value(carne,1). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s17, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s18, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s19, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s20, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s21, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,101). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s22, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s23, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,2). value(funghi_e_tartufi,0). value(pasta,501). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s24, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,105). value(carne,3). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s25, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,104). value(carne,5). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s26, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s27, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,3). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,507). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s28, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,106). value(carne,4). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,304). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s29, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s30, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,4). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,3). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s31, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,2). value(frutta,1). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled81s32, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,102). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s33, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,1). value(frutta,1). value(erbe_spezie_e_condimenti,105). value(carne,2). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s34, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,102). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s35, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,2). value(frutta,0). value(erbe_spezie_e_condimenti,105). value(carne,1). value(funghi_e_tartufi,0). value(pasta,508). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,5). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s36, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,4). value(erbe_spezie_e_condimenti,107). value(carne,4). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s37, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,1). value(frutta,0). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,303). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,1). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s38, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,3). value(erbe_spezie_e_condimenti,103). value(carne,1). value(funghi_e_tartufi,0). value(pasta,504). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,5). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled81s39, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,1). value(frutta,5). value(erbe_spezie_e_condimenti,107). value(carne,3). value(funghi_e_tartufi,0). value(pasta,505). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,305). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s40, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,2). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,4). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled81s41, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,3). value(frutta,3). value(erbe_spezie_e_condimenti,104). value(carne,4). value(funghi_e_tartufi,0). value(pasta,510). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,307). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled81s42, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,2). value(frutta,2). value(erbe_spezie_e_condimenti,103). value(carne,3). value(funghi_e_tartufi,0). value(pasta,502). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,302). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled81s43, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,3). value(frutta,4). value(erbe_spezie_e_condimenti,105). value(carne,0). value(funghi_e_tartufi,0). value(pasta,506). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,2). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled81s44, {}, {}, {category(3). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,5). value(frutta,3). value(erbe_spezie_e_condimenti,107). value(carne,3). value(funghi_e_tartufi,0). value(pasta,503). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,306). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,3). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s0, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,201). value(frutta,1). value(erbe_spezie_e_condimenti,205). value(carne,202). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s1, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,201). value(frutta,2). value(erbe_spezie_e_condimenti,204). value(carne,201). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s2, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,203). value(frutta,3). value(erbe_spezie_e_condimenti,204). value(carne,202). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s3, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,202). value(frutta,2). value(erbe_spezie_e_condimenti,205). value(carne,201). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s4, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,203). value(frutta,3). value(erbe_spezie_e_condimenti,202). value(carne,201). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s5, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,201). value(frutta,1). value(erbe_spezie_e_condimenti,203). value(carne,200). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s6, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,201). value(frutta,1). value(erbe_spezie_e_condimenti,204). value(carne,202). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,1). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled23s7, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,201). value(frutta,2). value(erbe_spezie_e_condimenti,202). value(carne,201). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled23s8, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,204). value(frutta,3). value(erbe_spezie_e_condimenti,203). value(carne,203). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s9, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,203). value(frutta,3). value(erbe_spezie_e_condimenti,202). value(carne,201). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s10, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,202). value(frutta,3). value(erbe_spezie_e_condimenti,203). value(carne,202). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,404). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled23s11, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,203). value(frutta,3). value(erbe_spezie_e_condimenti,205). value(carne,200). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s12, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,204). value(frutta,0). value(erbe_spezie_e_condimenti,204). value(carne,203). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s13, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,201). value(frutta,2). value(erbe_spezie_e_condimenti,205). value(carne,200). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s14, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,202). value(frutta,3). value(erbe_spezie_e_condimenti,204). value(carne,204). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s15, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,204). value(frutta,4). value(erbe_spezie_e_condimenti,203). value(carne,203). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s16, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,202). value(frutta,2). value(erbe_spezie_e_condimenti,205). value(carne,202). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled23s17, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,203). value(frutta,0). value(erbe_spezie_e_condimenti,203). value(carne,200). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s18, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,202). value(frutta,2). value(erbe_spezie_e_condimenti,205). value(carne,202). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s19, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,201). value(frutta,1). value(erbe_spezie_e_condimenti,203). value(carne,202). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s20, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,202). value(frutta,3). value(erbe_spezie_e_condimenti,205). value(carne,203). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s21, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,201). value(frutta,3). value(erbe_spezie_e_condimenti,205). value(carne,200). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled23s22, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,204). value(frutta,0). value(erbe_spezie_e_condimenti,206). value(carne,203). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,7). value(bollitura,0). value(rosolatura,0). value(frittura,4). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s23, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,202). value(frutta,2). value(erbe_spezie_e_condimenti,205). value(carne,202). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s24, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,202). value(frutta,3). value(erbe_spezie_e_condimenti,205). value(carne,202). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s25, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,203). value(frutta,3). value(erbe_spezie_e_condimenti,206). value(carne,201). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled23s26, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,4). value(uova,0). value(farinacei,203). value(frutta,5). value(erbe_spezie_e_condimenti,206). value(carne,203). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s27, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,5). value(uova,0). value(farinacei,203). value(frutta,2). value(erbe_spezie_e_condimenti,203). value(carne,203). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s28, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,202). value(frutta,1). value(erbe_spezie_e_condimenti,203). value(carne,201). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s29, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,201). value(frutta,3). value(erbe_spezie_e_condimenti,202). value(carne,201). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s30, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,200). value(frutta,2). value(erbe_spezie_e_condimenti,202). value(carne,202). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s31, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,202). value(frutta,1). value(erbe_spezie_e_condimenti,202). value(carne,201). value(funghi_e_tartufi,0). value(pasta,1). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s32, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,202). value(frutta,2). value(erbe_spezie_e_condimenti,204). value(carne,203). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s33, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,202). value(frutta,3). value(erbe_spezie_e_condimenti,202). value(carne,203). value(funghi_e_tartufi,0). value(pasta,2). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s34, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,203). value(frutta,1). value(erbe_spezie_e_condimenti,204). value(carne,200). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s35, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,203). value(frutta,2). value(erbe_spezie_e_condimenti,203). value(carne,205). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,6). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,1).} ).
#pos(sampled23s36, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,3). value(uova,0). value(farinacei,203). value(frutta,2). value(erbe_spezie_e_condimenti,206). value(carne,202). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s37, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,203). value(frutta,1). value(erbe_spezie_e_condimenti,206). value(carne,202). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s38, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,202). value(frutta,1). value(erbe_spezie_e_condimenti,203). value(carne,202). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,5). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled23s39, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,202). value(frutta,2). value(erbe_spezie_e_condimenti,203). value(carne,201). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,401). value(cottura_a_fiamma,0). value(stufato,2).} ).
#pos(sampled23s40, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,201). value(frutta,2). value(erbe_spezie_e_condimenti,202). value(carne,201). value(funghi_e_tartufi,0). value(pasta,5). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s41, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,203). value(frutta,0). value(erbe_spezie_e_condimenti,205). value(carne,201). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,2). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s42, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,1). value(uova,0). value(farinacei,201). value(frutta,2). value(erbe_spezie_e_condimenti,204). value(carne,204). value(funghi_e_tartufi,0). value(pasta,3). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,2). value(bollitura,0). value(rosolatura,0). value(frittura,1). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,3).} ).
#pos(sampled23s43, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,200). value(frutta,3). value(erbe_spezie_e_condimenti,204). value(carne,202). value(funghi_e_tartufi,0). value(pasta,4). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,4). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,402). value(cottura_a_fiamma,0). value(stufato,4).} ).
#pos(sampled23s44, {}, {}, {category(5). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,2). value(uova,0). value(farinacei,203). value(frutta,0). value(erbe_spezie_e_condimenti,202). value(carne,202). value(funghi_e_tartufi,0). value(pasta,6). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,3). value(bollitura,0). value(rosolatura,0). value(frittura,3). value(marinatura,0). value(mantecatura,0). value(forno,403). value(cottura_a_fiamma,0). value(stufato,1).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@1, sampled81s0, sampled23s0, >).
#brave_ordering(o2@1, sampled81s1, sampled23s1, >).
#brave_ordering(o3@2, sampled81s2, sampled23s2, >).
#brave_ordering(o4@3, sampled81s3, sampled23s3, >).
#brave_ordering(o5@2, sampled81s4, sampled23s4, >).
#brave_ordering(o6@1, sampled81s5, sampled23s5, >).
#brave_ordering(o7@1, sampled81s6, sampled23s6, >).
#brave_ordering(o8@2, sampled81s7, sampled23s7, >).
#brave_ordering(o9@1, sampled81s8, sampled23s8, >).
#brave_ordering(o10@1, sampled81s9, sampled23s9, >).
#brave_ordering(o11@2, sampled81s10, sampled23s10, >).
#brave_ordering(o12@2, sampled81s11, sampled23s11, >).
#brave_ordering(o13@2, sampled81s12, sampled23s12, >).
#brave_ordering(o14@1, sampled81s13, sampled23s13, >).
#brave_ordering(o15@2, sampled81s14, sampled23s14, >).
#brave_ordering(o16@1, sampled81s15, sampled23s15, >).
#brave_ordering(o17@1, sampled81s16, sampled23s16, >).
#brave_ordering(o18@2, sampled81s17, sampled23s17, >).
#brave_ordering(o19@1, sampled81s18, sampled23s18, >).
#brave_ordering(o20@1, sampled81s19, sampled23s19, >).
#brave_ordering(o21@2, sampled81s20, sampled23s20, >).
#brave_ordering(o22@1, sampled81s21, sampled23s21, >).
#brave_ordering(o23@1, sampled81s22, sampled23s22, >).
#brave_ordering(o24@2, sampled81s23, sampled23s23, >).
#brave_ordering(o25@1, sampled81s24, sampled23s24, >).
#brave_ordering(o26@1, sampled81s25, sampled23s25, >).
#brave_ordering(o27@1, sampled81s26, sampled23s26, >).
#brave_ordering(o28@1, sampled81s27, sampled23s27, >).
#brave_ordering(o29@2, sampled81s28, sampled23s28, >).
#brave_ordering(o30@2, sampled81s29, sampled23s29, >).
#brave_ordering(o31@2, sampled81s30, sampled23s30, >).
#brave_ordering(o32@2, sampled81s31, sampled23s31, >).
#brave_ordering(o33@2, sampled81s32, sampled23s32, >).
#brave_ordering(o34@2, sampled81s33, sampled23s33, >).
#brave_ordering(o35@2, sampled81s34, sampled23s34, >).
#brave_ordering(o36@1, sampled81s35, sampled23s35, >).
#brave_ordering(o37@1, sampled81s36, sampled23s36, >).
#brave_ordering(o38@2, sampled81s37, sampled23s37, >).
#brave_ordering(o39@2, sampled81s38, sampled23s38, >).
#brave_ordering(o40@1, sampled81s39, sampled23s39, >).
#brave_ordering(o41@2, sampled81s40, sampled23s40, >).
#brave_ordering(o42@1, sampled81s41, sampled23s41, >).
#brave_ordering(o43@2, sampled81s42, sampled23s42, >).
#brave_ordering(o44@1, sampled81s43, sampled23s43, >).
#brave_ordering(o45@2, sampled81s44, sampled23s44, >).
