#pos(sampled33s0, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s1, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s2, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s3, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s4, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s5, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s6, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s7, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s8, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s9, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s10, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s11, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s12, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s13, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s14, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s15, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s16, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s17, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s18, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s19, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s20, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s21, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s22, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s23, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s24, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s25, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s26, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s27, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s28, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s29, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s30, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s31, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s32, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s33, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s34, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s35, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s36, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s37, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s38, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s39, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s40, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s41, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s42, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s43, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled33s44, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,10). value(carne,30). value(funghi_e_tartufi,0). value(pasta,50). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,20). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s0, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s1, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s2, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s3, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s4, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s5, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s6, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s7, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s8, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s9, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s10, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s11, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s12, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s13, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s14, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s15, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s16, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s17, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s18, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s19, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s20, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s21, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s22, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s23, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s24, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s25, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s26, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s27, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s28, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s29, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s30, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s31, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s32, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s33, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s34, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s35, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s36, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s37, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s38, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s39, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s40, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s41, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s42, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s43, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).
#pos(sampled54s44, {}, {}, {category(0). value(cost,0). value(difficulty,0). value(prepTime,0). value(cereali,0). value(latticini,0). value(uova,0). value(farinacei,0). value(frutta,0). value(erbe_spezie_e_condimenti,30). value(carne,0). value(funghi_e_tartufi,0). value(pasta,0). value(pesce,0). value(dolcificanti,0). value(verdure_e_ortaggi,80). value(bollitura,0). value(rosolatura,0). value(frittura,0). value(marinatura,0). value(mantecatura,0). value(forno,0). value(cottura_a_fiamma,0). value(stufato,0).} ).


#maxv(1).
#maxp(5).

#modeo(1, value(const(val), var(val))).
#modeo(1, category(const(mg)), (positive)).
#weight(val).
#weight(1).
#weight(-1).
#constant(val, category).
#constant(val, cost).
#constant(val, difficulty).
#constant(val, prepTime).
#constant(mg, 1).
#constant(mg, 2).
#constant(mg, 3).
#constant(mg, 4).
#constant(mg, 5).
#constant(val, cereali).
#constant(val, latticini).
#constant(val, uova).
#constant(val, farinacei).
#constant(val, frutta).
#constant(val, erbe_spezie_e_condimenti).
#constant(val, carne).
#constant(val, funghi_e_tartufi).
#constant(val, pasta).
#constant(val, pesce).
#constant(val, dolcificanti).
#constant(val, verdure_e_ortaggi).
#constant(val, bollitura).
#constant(val, rosolatura).
#constant(val, frittura).
#constant(val, marinatura).
#constant(val, mantecatura).
#constant(val, forno).
#constant(val, cottura_a_fiamma).
#constant(val, stufato).

#brave_ordering(o1@1, sampled33s0, sampled54s0, =).
#brave_ordering(o2@1, sampled33s1, sampled54s1, <).
#brave_ordering(o3@1, sampled33s2, sampled54s2, <).
#brave_ordering(o4@1, sampled33s3, sampled54s3, <).
#brave_ordering(o5@1, sampled33s4, sampled54s4, <).
#brave_ordering(o6@1, sampled33s5, sampled54s5, >).
#brave_ordering(o7@1, sampled33s6, sampled54s6, <).
#brave_ordering(o8@1, sampled33s7, sampled54s7, >).
#brave_ordering(o9@1, sampled33s8, sampled54s8, <).
#brave_ordering(o10@1, sampled33s9, sampled54s9, <).
#brave_ordering(o11@1, sampled33s10, sampled54s10, <).
#brave_ordering(o12@1, sampled33s11, sampled54s11, <).
#brave_ordering(o13@1, sampled33s12, sampled54s12, >).
#brave_ordering(o14@1, sampled33s13, sampled54s13, <).
#brave_ordering(o15@1, sampled33s14, sampled54s14, <).
#brave_ordering(o16@1, sampled33s15, sampled54s15, <).
#brave_ordering(o17@1, sampled33s16, sampled54s16, <).
#brave_ordering(o18@1, sampled33s17, sampled54s17, <).
#brave_ordering(o19@1, sampled33s18, sampled54s18, <).
#brave_ordering(o20@1, sampled33s19, sampled54s19, <).
#brave_ordering(o21@1, sampled33s20, sampled54s20, <).
#brave_ordering(o22@1, sampled33s21, sampled54s21, <).
#brave_ordering(o23@1, sampled33s22, sampled54s22, <).
#brave_ordering(o24@1, sampled33s23, sampled54s23, <).
#brave_ordering(o25@1, sampled33s24, sampled54s24, <).
#brave_ordering(o26@1, sampled33s25, sampled54s25, <).
#brave_ordering(o27@1, sampled33s26, sampled54s26, <).
#brave_ordering(o28@1, sampled33s27, sampled54s27, =).
#brave_ordering(o29@1, sampled33s28, sampled54s28, <).
#brave_ordering(o30@1, sampled33s29, sampled54s29, >).
#brave_ordering(o31@1, sampled33s30, sampled54s30, <).
#brave_ordering(o32@1, sampled33s31, sampled54s31, >).
#brave_ordering(o33@1, sampled33s32, sampled54s32, <).
#brave_ordering(o34@1, sampled33s33, sampled54s33, <).
#brave_ordering(o35@1, sampled33s34, sampled54s34, >).
#brave_ordering(o36@1, sampled33s35, sampled54s35, <).
#brave_ordering(o37@1, sampled33s36, sampled54s36, <).
#brave_ordering(o38@1, sampled33s37, sampled54s37, >).
#brave_ordering(o39@1, sampled33s38, sampled54s38, >).
#brave_ordering(o40@1, sampled33s39, sampled54s39, >).
#brave_ordering(o41@1, sampled33s40, sampled54s40, >).
#brave_ordering(o42@1, sampled33s41, sampled54s41, >).
#brave_ordering(o43@1, sampled33s42, sampled54s42, >).
#brave_ordering(o44@1, sampled33s43, sampled54s43, <).
#brave_ordering(o45@1, sampled33s44, sampled54s44, <).
